### ISSUE TITLE
Study Group Map improvements

### ISSUE THREAD

**Issue by auremoser** [mozillascience/studyGroup-GSOC#3]
## Description

The current [Mozilla Study Group Page](https://science.mozilla.org/programs/studygroups) includes a map built with [Carto](https://carto.com/), we'd like to solicit improvements to the map, or other ways to highlight Study Group contributors globally.

## Process

[ordered list the process to finding and recreating the issue, example below]

1. Step 1: User visits the Study Group Project page at science.mozilla.or (Navigation: Programs>StudyGroups)
2. Step 2: User views the map (JS + Carto)
3. Step 3: User scrolls down the page and clicks to unroll the Study Group list under a region with links to individual groups (Django/Python)

## Expected result

Ideally, as it does now, the Study Group map would help users find out where Study Groups are all over the world and how to contact them or participate in a local study group.

## Current result

Right now, the map displays Study Groups whose locations we know, which is hard because not all forks of the [Study Group Project](https://github.com/mozillascience/studyGroup) have profiles with locations. 

## Possible Fix

1. Soliciting locations from all Study Group forks and collecting them in one spreadsheet would be great (see [test map data](data/whereweare.geojson) for formatting)
2. UI improvements to the map are also welcome
3. A simple embed fix for the current embedded map (which would eliminate the box shadow that currently outlines the top and left sides of the map would also be great.

## Image

![screen shot 2017-03-22 at 1 24 53 pm](https://cloud.githubusercontent.com/assets/1559703/24211251/d3856b24-0f01-11e7-9765-9e617341f1a6.png)

----

## References

* [Mozilla Study Group Webpage](https://science.mozilla.org/programs/studygroups) - where the map is currently embedded
* [Study Group Project](https://github.com/mozillascience/studyGroup) - where the map data comes from (forks of this project)
* [Test Map Data](https://github.com/mozillascience/studyGroup-GSOC/blob/master/data/whereweare.geojson) - geojson of existing map data for testing to make new maps, or for copying formatting for additional data

**Comment by WW-Web-Infra** [comment]
@auremoser "test map data" has no link

**Comment by auremoser** [comment]
Updated @AnamikaD !

**Comment by oak11** [comment]
Hi @auremoser , I want to contribute to the project for GSoC. Can I take up this bug to solve?

**Comment by auremoser** [comment]
Sure, you're welcome to get started if you'd like @oak11 !

**Comment by thobhanifreddy** [comment]
Is it necessary to use carto? or we can use something else like . We can also make each location [leafletjs](http://leafletjs.com/) which will give details about that study group like upcoming events.

**Comment by auremoser** [comment]
Yes totally @thobhanifreddy , we are open to suggestions. Carto's library includes leaflet actually, so it's more about the visual preference and flexibility desired for the map, Carto comes with a lot of cool UI additions (which we're not maximally using in the current map). Anything that can process Geojson is welcome!

**Comment by parimatrix** [comment]
Hi. I noticed the iframe shadow problem(top and left side of map) on the Mozilla Science group site. I fixed it with a minor edit. Am posting the screenshots. But can you please help where I can put up a PR for the same issue. Thanks.
![screenshot 3](https://user-images.githubusercontent.com/25114873/28666735-46aba9e0-72e6-11e7-814b-0572f1403ceb.png)
![screenshot 4](https://user-images.githubusercontent.com/25114873/28666736-46afd628-72e6-11e7-91e3-d71a9f37a8dd.png)

**Comment by WW-Web-Infra** [comment]
@parimatrix Thank you so much !! You can make the PR here : https://github.com/mozilla/science.mozilla.org

@auremoser : Please check this!
